## Configuration Apache
web:
   restart: always
   build: apache
   ports:
      - "8080:80"
   volumes:
      - ./www:/var/www/
      - ./php.ini:/etc/php/5.6/apache2/conf.d/30-custom.ini
      - ./sites:/etc/apache2/sites-enabled
   environment:
      - ALLOW_OVERRIDE=true
   links:
      - db:db
      - maildev:maildev

db:
 image: mysql
 restart: always
 volumes:
  - ./mysql:/var/lib/mysql
  - ./my.cnf:/etc/mysql/mysql.conf.d/mysqld.cnf
 environment:
  - MYSQL_ROOT_PASSWORD=root

maildev:
 restart: always
 image: djfarrelly/maildev:1.0.0-rc2
 ports:
  - "1080:80"
